---

- name: enabling rewriting urls for {{ wp_site_local.site }} in wordpress
  shell:
    cmd: |
      /usr/local/bin/wp rewrite structure '/%year%/%monthnum%/%postname%/' --path="{{ web_docroot }}" --allow-root
  register: wp_rewrite_configure
  # changed_when: '"Theme already installed" not in wp_rewrite_configure.stdout'
  changed_when: false
