---

# sudo su - www-data -s /bin/bash -c 'strace -f -e file /usr/local/bin/wp --debug  theme install revelar --debug --path="/'

- name: give permission to web user to update themes
  file:
    path: "{{ web_docroot }}/wp-content/upgrade"
    state: directory
    owner: "{{ webserver_user }}"
    group: root
    mode: 0755

- name: "install themes for {{ wp_site_local.url }}"
  become: yes
  become_user: "{{ webserver_user }}"
  shell: |
    id
    whoami
    /usr/local/bin/wp theme install {{ wp_site_theme }} --path="{{ web_docroot }}"
  with_items: "{{ wp_site_local.themes }}"
  loop_control:
    loop_var: wp_site_theme
  when: wp_site_local.themes is defined and wp_site_local.themes
  register: wp_themes_install
  changed_when: '"Theme already installed." not in wp_themes_install.stdout'

- name: "install theme for {{ wp_site }}"
  shell: |
    /usr/local/bin/wp theme install {{ wp_site_local.theme }} --path="{{ web_docroot }}"  --allow-root
    /usr/local/bin/wp theme activate {{  wp_site_local.theme }} --path="{{ web_docroot }}"  --allow-root
  when: wp_site_local.theme is defined and wp_site_local.theme
  register: wp_theme_install
  changed_when: '"Theme already installed" not in wp_theme_install.stdout'
