---

- tags: [ wordpress ]
  block:

    - name: configure admin and supervisor user
      include_tasks: configure-admins.yml

    - name: fix the permissions on the site files
      include_tasks: configure-permissions.yml

    - name: configure url rewriting
      include_tasks: configure-rewriting.yml

    - name: install and activate any plugins requested
      include_tasks: configure-plugins.yml

    - name: install any themes, and set the `theme` as the active on
      include_tasks: configure-theme.yml
