---

- tags: [ wordpress, wordpress-cli ]
  block:

    - name: check whether the wordpress has already been installed
      shell:
        cmd: |
          /usr/local/bin/wp core is-installed --allow-root --path="{{ web_docroot }}"

          retcode=$?

          if [ $retcode -eq 1 ]; then
            echo "not-installed"
          elif [ $retcode -eq 0 ]; then
            echo "is-installed"
          else
            echo "There was some other error AND assuming not-installed"
          fi

      changed_when: "'is-installed' not in wp_is_install.stdout"
      register: wp_is_install

    - name: "install wordpress => {{ web_docroot }}"
      shell:
        cmd: |
          if [ -d "{{ web_docroot }}" ]; then
            echo "doc root exists ({{ web_docroot }})"
            cd "{{ web_docroot }}"

            if [ ! -d "{{ web_docroot }}/wp-admin" ]; then
              echo "wp-admin not exists ({{ web_docroot }}/wp-admin)"
              echo Downloading core
              /usr/local/bin/wp core download  --allow-root || exit $?
              echo $?
            fi

            # try that again...
            if [ -d "{{ web_docroot }}/wp-admin" ]; then
              echo "wp-admin exists ({{ web_docroot }}/wp-admin)"
              if /usr/local/bin/wp core is-installed --allow-root ; then
                echo "core is-installed ALREADY";
              else
                echo "installing CORE to {{ web_docroot }}";
                /usr/local/bin/wp core install --url={{ wp_hostname }} --title="{{ wp_title |default( wp_hostname)  }} Wordpress" --admin_user=supervisor --admin_password=stroccsngpadssword --admin_email=info@example.com --allow-root || exit $?
              fi
            fi
          fi
          echo $?
        # creates:
      # args:
      #   chdir: /var/www/
      register: wp_install
      changed_when: "'WordPress installed successfully' in wp_install.stdout"
      when: wp_is_install.changed


    - name: debug output
      debug: msg={{ wp_install }}
      # curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar

      # wp core install --url=example.com --title=Example --admin_user=supervisor --admin_password=strongpassword --admin_email=info@example.com
