---

- tags: [ wordpress, wordpress-cli ]
  block:

    #                              _ _
    #   __      ___ __         ___| (_)
    #   \ \ /\ / / '_ \ _____ / __| | |
    #    \ V  V /| |_) |_____| (__| | |
    #     \_/\_/ | .__/       \___|_|_|
    #            |_|

    - name: Download WordPress-cli
      get_url:
        url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        dest: /opt/wp-cli.phar
        validate_certs: no

    - file:
        path: /opt/wp-cli.phar
        owner: root
        group: root
        mode: 0755

    - file:
        src: /opt/wp-cli.phar
        dest: /usr/local/bin/wp
        state: link

    - user:
        name: "{{ webserver_user }}"
      register: webserver_user_registered

    - debug:
        var: webserver_user_registered

    - name: create the .wp-cli directory, as apache_user doesn't own /var/www
      file:
        name: "{{ webserver_user_registered.home }}/.wp-cli"
        state: directory
        owner: "{{ webserver_user }}"
        group: "{{ webserver_user }}"
